language: go
go:
  - 1.4

install:
  - go get -v -t ./...
  - go install github.com/onsi/ginkgo/ginkgo
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go install github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --trace --race --compilers=2

after_success:
  - goveralls -repotoken $COVERALLS_TOKEN

services:
  - mongodb
