language: go
go:
  - 1.4

install:
  - go get -v -t ./...
  - go install github.com/onsi/ginkgo/ginkgo

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --trace --race --compilers=2

services:
  - mongodb
