language: go
go:
  - 1.4

install:
  - go get -v -t ./...

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --compilers=2

services:
  - mongodb
