language: go
go:
  - 1.4

install:
  - go get -v -t ./...
  - go get github.com/axw/gocov/gocov
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --trace --race --compilers=2 -cover

after_success:
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci

services:
  - mongodb
