language: go
go:
  - release

install:
  - go get -v -t ./...
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$HOME/gopath/bin:$PATH


before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --compilers=2
