language: go
go:
  - 1.4

install:
  - go get -v -t ./...
  - go install github.com/onsi/ginkgo/ginkgo

before_script:
- "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --trace --race --compilers=2

services:
  - mongodb
